services:
  db:
    container_name: itk_db
    image: postgres:17.6
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - itk_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB' ]
      interval: 5s
      retries: 5
      timeout: 10s

  app:
    container_name: itk_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "${PORT_API}:${PORT_API}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    command: >
      sh -c 'uv run python3 manage.py collectstatic --noinput &&
             uv run python3 manage.py makemigrations --noinput &&
             uv run python3 manage.py migrate &&
             uv run python3 manage.py create_test_data &&
             uv run gunicorn config.wsgi:application --bind 0.0.0.0:${PORT_API} --workers 5 --timeout 60 --preload'

  nginx:
    image: nginx:1.29.1
    container_name: itk_nginx
    restart: unless-stopped
    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static

volumes:
  itk_data: